@startuml
'https://plantuml.com/sequence-diagram


class ToDoLists
{
    main()
    start()
    refreshAccordion()
    scrollWheelSetup()
    parse()
}

class ToDoListController
{
    addToListClicked()
    removeFromListClicked()
    clearListClicked()
    editNameOfItemClicked()
    editNameOfItemClicked()
    editDescOfItemClicked()
    editDateOfItemClicked()
    editDateOfItemClicked()
    markCompleteClicked()
    allItemsClicked()
    completeItemsClicked()
    incompleteItemsClicked()
    importListClicked()
    arrayToList()
    ListToFile()
    exportListClicked()
    exportListClicked()
    'needs readme.md'
}

class itemFormat
{
    name
    desc
    completed
    -index
}

javafx.Application <|-- ToDoLists
ToDoLists - ToDoListController
ToDoLists - itemFormat
itemFormat - ToDoListController

@enduml